language: c
compiler:
  - gcc
# Change this to your needs
script: ./build.sh -j$(nproc) && tar czvf ffmpeg.tar.gz target/

deploy:
  provider: releases
  api_key:
    secure: I0EWMVDiP1YZ8a7EK9yGxgcWLejaqr+YAHXgROmiof5SSyD3AmyYjzk13uA2mlMay0BI/zxAZRqGP/c48C8j+/7Zcdc8whwMQ8tnz5vffqtYQGFouiwZtIZtEbYpZOANHkgkh8w5qYqhhxHgMFM4EU4nkjh+PkICIYT2xM8E5mk=
  file: ffmpeg.tar.gz
  on:
    repo: mayli/ffmpeg-static-build
    tags: true
